---
refresh_interval: 60 # seconds
urls:
  - https://www.pccomponentes.com/amd-ryzen-5-3600-36ghz-box # test item (in stock)
  - https://www.pccomponentes.com/pny-geforce-rtx-3080-xlr8-gaming-revel-epic-x-rgb-triple-fan-edition-10gb-gddr6x
...
